/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as ProfilRouteImport } from './routes/profil';
import { Route as ListsRouteImport } from './routes/lists';
import { Route as FilmsRouteImport } from './routes/films';
import { Route as DiscussionRouteImport } from './routes/discussion';
import { Route as IndexRouteImport } from './routes/index';
import { Route as FilmsIndexRouteImport } from './routes/films.index';
import { Route as FilmsCategorieRouteImport } from './routes/films.$categorie';
import { Route as FilmIdRouteImport } from './routes/film.$id';

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any);
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any);
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any);
const DiscussionRoute = DiscussionRouteImport.update({
  id: '/discussion',
  path: '/discussion',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const FilmsIndexRoute = FilmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FilmsRoute,
} as any);
const FilmsCategorieRoute = FilmsCategorieRouteImport.update({
  id: '/$categorie',
  path: '/$categorie',
  getParentRoute: () => FilmsRoute,
} as any);
const FilmIdRoute = FilmIdRouteImport.update({
  id: '/film/$id',
  path: '/film/$id',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/discussion': typeof DiscussionRoute;
  '/films': typeof FilmsRouteWithChildren;
  '/lists': typeof ListsRoute;
  '/profil': typeof ProfilRoute;
  '/film/$id': typeof FilmIdRoute;
  '/films/$categorie': typeof FilmsCategorieRoute;
  '/films/': typeof FilmsIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/discussion': typeof DiscussionRoute;
  '/lists': typeof ListsRoute;
  '/profil': typeof ProfilRoute;
  '/film/$id': typeof FilmIdRoute;
  '/films/$categorie': typeof FilmsCategorieRoute;
  '/films': typeof FilmsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/discussion': typeof DiscussionRoute;
  '/films': typeof FilmsRouteWithChildren;
  '/lists': typeof ListsRoute;
  '/profil': typeof ProfilRoute;
  '/film/$id': typeof FilmIdRoute;
  '/films/$categorie': typeof FilmsCategorieRoute;
  '/films/': typeof FilmsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/discussion'
    | '/films'
    | '/lists'
    | '/profil'
    | '/film/$id'
    | '/films/$categorie'
    | '/films/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/discussion' | '/lists' | '/profil' | '/film/$id' | '/films/$categorie' | '/films';
  id:
    | '__root__'
    | '/'
    | '/discussion'
    | '/films'
    | '/lists'
    | '/profil'
    | '/film/$id'
    | '/films/$categorie'
    | '/films/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DiscussionRoute: typeof DiscussionRoute;
  FilmsRoute: typeof FilmsRouteWithChildren;
  ListsRoute: typeof ListsRoute;
  ProfilRoute: typeof ProfilRoute;
  FilmIdRoute: typeof FilmIdRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil';
      path: '/profil';
      fullPath: '/profil';
      preLoaderRoute: typeof ProfilRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/lists': {
      id: '/lists';
      path: '/lists';
      fullPath: '/lists';
      preLoaderRoute: typeof ListsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/films': {
      id: '/films';
      path: '/films';
      fullPath: '/films';
      preLoaderRoute: typeof FilmsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/discussion': {
      id: '/discussion';
      path: '/discussion';
      fullPath: '/discussion';
      preLoaderRoute: typeof DiscussionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/films/': {
      id: '/films/';
      path: '/';
      fullPath: '/films/';
      preLoaderRoute: typeof FilmsIndexRouteImport;
      parentRoute: typeof FilmsRoute;
    };
    '/films/$categorie': {
      id: '/films/$categorie';
      path: '/$categorie';
      fullPath: '/films/$categorie';
      preLoaderRoute: typeof FilmsCategorieRouteImport;
      parentRoute: typeof FilmsRoute;
    };
    '/film/$id': {
      id: '/film/$id';
      path: '/film/$id';
      fullPath: '/film/$id';
      preLoaderRoute: typeof FilmIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface FilmsRouteChildren {
  FilmsCategorieRoute: typeof FilmsCategorieRoute;
  FilmsIndexRoute: typeof FilmsIndexRoute;
}

const FilmsRouteChildren: FilmsRouteChildren = {
  FilmsCategorieRoute: FilmsCategorieRoute,
  FilmsIndexRoute: FilmsIndexRoute,
};

const FilmsRouteWithChildren = FilmsRoute._addFileChildren(FilmsRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscussionRoute: DiscussionRoute,
  FilmsRoute: FilmsRouteWithChildren,
  ListsRoute: ListsRoute,
  ProfilRoute: ProfilRoute,
  FilmIdRoute: FilmIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
