/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as ResetPasswordRouteImport } from './routes/reset-password';
import { Route as ProfilRouteImport } from './routes/profil';
import { Route as MembersRouteImport } from './routes/members';
import { Route as ListsRouteImport } from './routes/lists';
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password';
import { Route as FilmsRouteImport } from './routes/films';
import { Route as DiscussionRouteImport } from './routes/discussion';
import { Route as IndexRouteImport } from './routes/index';
import { Route as FilmsIndexRouteImport } from './routes/films.index';
import { Route as UserIdRouteImport } from './routes/user.$id';
import { Route as PersonIdRouteImport } from './routes/person.$id';
import { Route as FilmsCategorieRouteImport } from './routes/films.$categorie';
import { Route as FilmIdRouteImport } from './routes/film.$id';

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any);
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any);
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any);
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any);
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any);
const DiscussionRoute = DiscussionRouteImport.update({
  id: '/discussion',
  path: '/discussion',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const FilmsIndexRoute = FilmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FilmsRoute,
} as any);
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any);
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any);
const FilmsCategorieRoute = FilmsCategorieRouteImport.update({
  id: '/$categorie',
  path: '/$categorie',
  getParentRoute: () => FilmsRoute,
} as any);
const FilmIdRoute = FilmIdRouteImport.update({
  id: '/film/$id',
  path: '/film/$id',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/discussion': typeof DiscussionRoute;
  '/films': typeof FilmsRouteWithChildren;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/lists': typeof ListsRoute;
  '/members': typeof MembersRoute;
  '/profil': typeof ProfilRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/settings': typeof SettingsRoute;
  '/film/$id': typeof FilmIdRoute;
  '/films/$categorie': typeof FilmsCategorieRoute;
  '/person/$id': typeof PersonIdRoute;
  '/user/$id': typeof UserIdRoute;
  '/films/': typeof FilmsIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/discussion': typeof DiscussionRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/lists': typeof ListsRoute;
  '/members': typeof MembersRoute;
  '/profil': typeof ProfilRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/settings': typeof SettingsRoute;
  '/film/$id': typeof FilmIdRoute;
  '/films/$categorie': typeof FilmsCategorieRoute;
  '/person/$id': typeof PersonIdRoute;
  '/user/$id': typeof UserIdRoute;
  '/films': typeof FilmsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/discussion': typeof DiscussionRoute;
  '/films': typeof FilmsRouteWithChildren;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/lists': typeof ListsRoute;
  '/members': typeof MembersRoute;
  '/profil': typeof ProfilRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/settings': typeof SettingsRoute;
  '/film/$id': typeof FilmIdRoute;
  '/films/$categorie': typeof FilmsCategorieRoute;
  '/person/$id': typeof PersonIdRoute;
  '/user/$id': typeof UserIdRoute;
  '/films/': typeof FilmsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/discussion'
    | '/films'
    | '/forgot-password'
    | '/lists'
    | '/members'
    | '/profil'
    | '/reset-password'
    | '/settings'
    | '/film/$id'
    | '/films/$categorie'
    | '/person/$id'
    | '/user/$id'
    | '/films/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/discussion'
    | '/forgot-password'
    | '/lists'
    | '/members'
    | '/profil'
    | '/reset-password'
    | '/settings'
    | '/film/$id'
    | '/films/$categorie'
    | '/person/$id'
    | '/user/$id'
    | '/films';
  id:
    | '__root__'
    | '/'
    | '/discussion'
    | '/films'
    | '/forgot-password'
    | '/lists'
    | '/members'
    | '/profil'
    | '/reset-password'
    | '/settings'
    | '/film/$id'
    | '/films/$categorie'
    | '/person/$id'
    | '/user/$id'
    | '/films/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DiscussionRoute: typeof DiscussionRoute;
  FilmsRoute: typeof FilmsRouteWithChildren;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  ListsRoute: typeof ListsRoute;
  MembersRoute: typeof MembersRoute;
  ProfilRoute: typeof ProfilRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
  SettingsRoute: typeof SettingsRoute;
  FilmIdRoute: typeof FilmIdRoute;
  PersonIdRoute: typeof PersonIdRoute;
  UserIdRoute: typeof UserIdRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/reset-password': {
      id: '/reset-password';
      path: '/reset-password';
      fullPath: '/reset-password';
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/profil': {
      id: '/profil';
      path: '/profil';
      fullPath: '/profil';
      preLoaderRoute: typeof ProfilRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/members': {
      id: '/members';
      path: '/members';
      fullPath: '/members';
      preLoaderRoute: typeof MembersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/lists': {
      id: '/lists';
      path: '/lists';
      fullPath: '/lists';
      preLoaderRoute: typeof ListsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/forgot-password': {
      id: '/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/films': {
      id: '/films';
      path: '/films';
      fullPath: '/films';
      preLoaderRoute: typeof FilmsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/discussion': {
      id: '/discussion';
      path: '/discussion';
      fullPath: '/discussion';
      preLoaderRoute: typeof DiscussionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/films/': {
      id: '/films/';
      path: '/';
      fullPath: '/films/';
      preLoaderRoute: typeof FilmsIndexRouteImport;
      parentRoute: typeof FilmsRoute;
    };
    '/user/$id': {
      id: '/user/$id';
      path: '/user/$id';
      fullPath: '/user/$id';
      preLoaderRoute: typeof UserIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/person/$id': {
      id: '/person/$id';
      path: '/person/$id';
      fullPath: '/person/$id';
      preLoaderRoute: typeof PersonIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/films/$categorie': {
      id: '/films/$categorie';
      path: '/$categorie';
      fullPath: '/films/$categorie';
      preLoaderRoute: typeof FilmsCategorieRouteImport;
      parentRoute: typeof FilmsRoute;
    };
    '/film/$id': {
      id: '/film/$id';
      path: '/film/$id';
      fullPath: '/film/$id';
      preLoaderRoute: typeof FilmIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface FilmsRouteChildren {
  FilmsCategorieRoute: typeof FilmsCategorieRoute;
  FilmsIndexRoute: typeof FilmsIndexRoute;
}

const FilmsRouteChildren: FilmsRouteChildren = {
  FilmsCategorieRoute: FilmsCategorieRoute,
  FilmsIndexRoute: FilmsIndexRoute,
};

const FilmsRouteWithChildren = FilmsRoute._addFileChildren(FilmsRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscussionRoute: DiscussionRoute,
  FilmsRoute: FilmsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ListsRoute: ListsRoute,
  MembersRoute: MembersRoute,
  ProfilRoute: ProfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  FilmIdRoute: FilmIdRoute,
  PersonIdRoute: PersonIdRoute,
  UserIdRoute: UserIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
