/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

<<<<<<< HEAD
import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MembersRouteImport } from './routes/members'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FilmsRouteImport } from './routes/films'
import { Route as DiscussionRouteImport } from './routes/discussion'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmsIndexRouteImport } from './routes/films.index'
import { Route as UserIdRouteImport } from './routes/user.$id'
import { Route as PersonIdRouteImport } from './routes/person.$id'
import { Route as FilmsCategorieRouteImport } from './routes/films.$categorie'
import { Route as FilmIdRouteImport } from './routes/film.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
=======
import { Route as rootRouteImport } from './routes/__root';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as ResetPasswordRouteImport } from './routes/reset-password';
import { Route as ProfilRouteImport } from './routes/profil';
import { Route as MembersRouteImport } from './routes/members';
import { Route as ListsRouteImport } from './routes/lists';
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password';
import { Route as FilmsRouteImport } from './routes/films';
import { Route as DiscussionRouteImport } from './routes/discussion';
import { Route as IndexRouteImport } from './routes/index';
import { Route as FilmsIndexRouteImport } from './routes/films.index';
import { Route as UserIdRouteImport } from './routes/user.$id';
import { Route as PersonIdRouteImport } from './routes/person.$id';
import { Route as FilmsCategorieRouteImport } from './routes/films.$categorie';
import { Route as FilmIdRouteImport } from './routes/film.$id';
>>>>>>> bc8023e (feat(frontend): add forgot and reset password UI)

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
<<<<<<< HEAD
} as any)
=======
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any);
>>>>>>> bc8023e (feat(frontend): add forgot and reset password UI)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
<<<<<<< HEAD
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
=======
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any);
>>>>>>> bc8023e (feat(frontend): add forgot and reset password UI)
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionRoute = DiscussionRouteImport.update({
  id: '/discussion',
  path: '/discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsIndexRoute = FilmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FilmsRoute,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsCategorieRoute = FilmsCategorieRouteImport.update({
  id: '/$categorie',
  path: '/$categorie',
  getParentRoute: () => FilmsRoute,
} as any)
const FilmIdRoute = FilmIdRouteImport.update({
  id: '/film/$id',
  path: '/film/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
<<<<<<< HEAD
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/discussion': typeof DiscussionRoute
  '/films': typeof FilmsRouteWithChildren
  '/help': typeof HelpRoute
  '/lists': typeof ListsRoute
  '/members': typeof MembersRoute
  '/privacy': typeof PrivacyRoute
  '/profil': typeof ProfilRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/film/$id': typeof FilmIdRoute
  '/films/$categorie': typeof FilmsCategorieRoute
  '/person/$id': typeof PersonIdRoute
  '/user/$id': typeof UserIdRoute
  '/films/': typeof FilmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/discussion': typeof DiscussionRoute
  '/help': typeof HelpRoute
  '/lists': typeof ListsRoute
  '/members': typeof MembersRoute
  '/privacy': typeof PrivacyRoute
  '/profil': typeof ProfilRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/film/$id': typeof FilmIdRoute
  '/films/$categorie': typeof FilmsCategorieRoute
  '/person/$id': typeof PersonIdRoute
  '/user/$id': typeof UserIdRoute
  '/films': typeof FilmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/discussion': typeof DiscussionRoute
  '/films': typeof FilmsRouteWithChildren
  '/help': typeof HelpRoute
  '/lists': typeof ListsRoute
  '/members': typeof MembersRoute
  '/privacy': typeof PrivacyRoute
  '/profil': typeof ProfilRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/film/$id': typeof FilmIdRoute
  '/films/$categorie': typeof FilmsCategorieRoute
  '/person/$id': typeof PersonIdRoute
  '/user/$id': typeof UserIdRoute
  '/films/': typeof FilmsIndexRoute
=======
  '/': typeof IndexRoute;
  '/discussion': typeof DiscussionRoute;
  '/films': typeof FilmsRouteWithChildren;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/lists': typeof ListsRoute;
  '/members': typeof MembersRoute;
  '/profil': typeof ProfilRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/settings': typeof SettingsRoute;
  '/film/$id': typeof FilmIdRoute;
  '/films/$categorie': typeof FilmsCategorieRoute;
  '/person/$id': typeof PersonIdRoute;
  '/user/$id': typeof UserIdRoute;
  '/films/': typeof FilmsIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/discussion': typeof DiscussionRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/lists': typeof ListsRoute;
  '/members': typeof MembersRoute;
  '/profil': typeof ProfilRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/settings': typeof SettingsRoute;
  '/film/$id': typeof FilmIdRoute;
  '/films/$categorie': typeof FilmsCategorieRoute;
  '/person/$id': typeof PersonIdRoute;
  '/user/$id': typeof UserIdRoute;
  '/films': typeof FilmsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/discussion': typeof DiscussionRoute;
  '/films': typeof FilmsRouteWithChildren;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/lists': typeof ListsRoute;
  '/members': typeof MembersRoute;
  '/profil': typeof ProfilRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/settings': typeof SettingsRoute;
  '/film/$id': typeof FilmIdRoute;
  '/films/$categorie': typeof FilmsCategorieRoute;
  '/person/$id': typeof PersonIdRoute;
  '/user/$id': typeof UserIdRoute;
  '/films/': typeof FilmsIndexRoute;
>>>>>>> bc8023e (feat(frontend): add forgot and reset password UI)
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-docs'
    | '/contact'
    | '/cookies'
    | '/discussion'
    | '/films'
<<<<<<< HEAD
    | '/help'
=======
    | '/forgot-password'
>>>>>>> bc8023e (feat(frontend): add forgot and reset password UI)
    | '/lists'
    | '/members'
    | '/privacy'
    | '/profil'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/auth/callback'
    | '/film/$id'
    | '/films/$categorie'
    | '/person/$id'
    | '/user/$id'
    | '/films/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-docs'
    | '/contact'
    | '/cookies'
    | '/discussion'
<<<<<<< HEAD
    | '/help'
=======
    | '/forgot-password'
>>>>>>> bc8023e (feat(frontend): add forgot and reset password UI)
    | '/lists'
    | '/members'
    | '/privacy'
    | '/profil'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/auth/callback'
    | '/film/$id'
    | '/films/$categorie'
    | '/person/$id'
    | '/user/$id'
    | '/films'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api-docs'
    | '/contact'
    | '/cookies'
    | '/discussion'
    | '/films'
<<<<<<< HEAD
    | '/help'
=======
    | '/forgot-password'
>>>>>>> bc8023e (feat(frontend): add forgot and reset password UI)
    | '/lists'
    | '/members'
    | '/privacy'
    | '/profil'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/auth/callback'
    | '/film/$id'
    | '/films/$categorie'
    | '/person/$id'
    | '/user/$id'
    | '/films/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
<<<<<<< HEAD
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DiscussionRoute: typeof DiscussionRoute
  FilmsRoute: typeof FilmsRouteWithChildren
  HelpRoute: typeof HelpRoute
  ListsRoute: typeof ListsRoute
  MembersRoute: typeof MembersRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfilRoute: typeof ProfilRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  FilmIdRoute: typeof FilmIdRoute
  PersonIdRoute: typeof PersonIdRoute
  UserIdRoute: typeof UserIdRoute
=======
  IndexRoute: typeof IndexRoute;
  DiscussionRoute: typeof DiscussionRoute;
  FilmsRoute: typeof FilmsRouteWithChildren;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  ListsRoute: typeof ListsRoute;
  MembersRoute: typeof MembersRoute;
  ProfilRoute: typeof ProfilRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
  SettingsRoute: typeof SettingsRoute;
  FilmIdRoute: typeof FilmIdRoute;
  PersonIdRoute: typeof PersonIdRoute;
  UserIdRoute: typeof UserIdRoute;
>>>>>>> bc8023e (feat(frontend): add forgot and reset password UI)
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
<<<<<<< HEAD
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/reset-password': {
      id: '/reset-password';
      path: '/reset-password';
      fullPath: '/reset-password';
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
>>>>>>> bc8023e (feat(frontend): add forgot and reset password UI)
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
<<<<<<< HEAD
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
      id: '/lists';
      path: '/lists';
      fullPath: '/lists';
      preLoaderRoute: typeof ListsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/forgot-password': {
      id: '/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
>>>>>>> bc8023e (feat(frontend): add forgot and reset password UI)
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussion': {
      id: '/discussion'
      path: '/discussion'
      fullPath: '/discussion'
      preLoaderRoute: typeof DiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/': {
      id: '/films/'
      path: '/'
      fullPath: '/films/'
      preLoaderRoute: typeof FilmsIndexRouteImport
      parentRoute: typeof FilmsRoute
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$categorie': {
      id: '/films/$categorie'
      path: '/$categorie'
      fullPath: '/films/$categorie'
      preLoaderRoute: typeof FilmsCategorieRouteImport
      parentRoute: typeof FilmsRoute
    }
    '/film/$id': {
      id: '/film/$id'
      path: '/film/$id'
      fullPath: '/film/$id'
      preLoaderRoute: typeof FilmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FilmsRouteChildren {
  FilmsCategorieRoute: typeof FilmsCategorieRoute
  FilmsIndexRoute: typeof FilmsIndexRoute
}

const FilmsRouteChildren: FilmsRouteChildren = {
  FilmsCategorieRoute: FilmsCategorieRoute,
  FilmsIndexRoute: FilmsIndexRoute,
}

const FilmsRouteWithChildren = FilmsRoute._addFileChildren(FilmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiDocsRoute: ApiDocsRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DiscussionRoute: DiscussionRoute,
  FilmsRoute: FilmsRouteWithChildren,
<<<<<<< HEAD
  HelpRoute: HelpRoute,
=======
  ForgotPasswordRoute: ForgotPasswordRoute,
>>>>>>> bc8023e (feat(frontend): add forgot and reset password UI)
  ListsRoute: ListsRoute,
  MembersRoute: MembersRoute,
  PrivacyRoute: PrivacyRoute,
  ProfilRoute: ProfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  FilmIdRoute: FilmIdRoute,
  PersonIdRoute: PersonIdRoute,
  UserIdRoute: UserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
